# Game Theory: Nash's Theorem
### Definition of Support
- For a given startegy $\sigma$, the support ($\sigma: \mathcal{S}(\sigma)$) is the set of strategies for which $\sigma_i>0$:
 - $i\in\mathcal{S}(\sigma)\Leftrightarrow \sigma_i > 0$

For example:
- If $\sigma=(1/3, 1/2, 0, 0, 1/6): \mathcal{S}(\sigma)=\{1, 2, 5\}$
- If $\sigma=(0, 0, 1, 0): \mathcal{S}(\sigma)=\{3\}$

In [2]:
import numpy as np
sigma = np.array([1/3, 1/2, 0, 0, 1/6])
np.where(sigma > 0)

(array([0, 1, 4]),)

In [3]:
sigma = np.array([0, 0, 1, 0])
np.where(sigma > 0)

(array([2]),)

### Definition of non-degenerate games
- A two player game where no mixed strategy of support size ($k$) has more than ($k$) pure best responses.

For example:
- $A = 
\begin{pmatrix}
    1 & 1 & 0\\
    2 & 3 & 0
\end{pmatrix}\qquad
B = 
\begin{pmatrix}
    1/2 & -1 & -1/2\\
    -1 & -1 & 2
\end{pmatrix}$

- Consider $\sigma_c=(0, 0, 1)$, we have $|\mathcal{S}(\sigma_c)|=1$ and:
 - $A\sigma_c^T = 
\begin{pmatrix}
    0\\
    0
\end{pmatrix}$

The number of pure responses to $\sigma_c$ is two, So the game is considered as a degenerate game.

In [8]:
A = np.array([[1, 1, 0], [2, 2, 0]])
sigma_c = np.array([0, 0, 1])
(np.dot(A, sigma_c))

array([0, 0])

### Support enumeration algorithm
For a non-degenerate two player game $(A,B)\in{\mathbb{R}^{m\times n}}^2$:
1. For all $1\leq k\leq \min(m, n);$

2. For all pairs of support $(I, J)$ with $|I|=|J|=k$

3. Solve the equations:
    - $\sum_{i\in I}{\sigma_{r}}_iB_{ij}=v\text{ for all }j\in J$
    
    - $\sum_{j\in J}A_{ij}{\sigma_{c}}_j=u\text{ for all }i\in I$
    
4. Solve the equations:
    - $\sum_{i=1}^{m}{\sigma_{r}}_i=1$ and ${\sigma_{r}}_i\geq 0$ for all $i$
    
    - $\sum_{j=1}^{n}{\sigma_{c}}_i=1$ and ${\sigma_{c}}_j\geq 0$ for all $j$
    
5. Check the best response condition

(Repeat steps 3,4,5 for all potential support pairs)

### 2 by 2 example of support enumeration
#### Using the two player game matching pennies game.
$A=
\begin{pmatrix}
1 & -1\\
-1 & 1
\end{pmatrix}\qquad
B=
\begin{pmatrix}
-1 & 1\\
1 & -1
\end{pmatrix}$

1. Consider $k=1$: in other words the pairs of pure best responses is equal to 1. We can identify these by looking at the best responses (underlined).
    - $A=
\begin{pmatrix}
\underline{1} & -1\\
-1 & \underline{1}
\end{pmatrix}\qquad
B=
\begin{pmatrix}
-1 & \underline{1}\\
\underline{1} & -1
\end{pmatrix}$

So there are no pairs:

1. Thus we start again with $k=2$

2. There is only one pair of best responses to be considered: $I=J=\{1, 2\}$

3. The equations we must solve:

    - $-{\sigma_{r}}_1+{\sigma_{r}}_2=v$
    
    - ${\sigma_{r}}_1-{\sigma_{r}}_2=v$
    
   And:
   
    - $-{\sigma_{c}}_1+{\sigma_{c}}_2=u$
    
    - ${\sigma_{c}}_1-{\sigma_{c}}_2=u$
    
   We dont know the values of $(u, v)$ so we solve:
   
    - $-{\sigma_{r}}_1+{\sigma_{r}}_2={\sigma_{r}}_1-{\sigma_{r}}_2$
    
    - ${\sigma_{c}}_1-{\sigma_{c}}_2=-{\sigma_{c}}_1+{\sigma_{c}}_2$
   
   Which returns:
   
    - ${\sigma_{r}}_1={\sigma_{r}}_2$
    
    - ${\sigma_{c}}_1={\sigma_{c}}_2$
   
4. Then:

 - $\sigma_{r}=(1/2, 1/2)$
 
 - $\sigma_{c}=(1/2, 1/2)$
 
5. Finally we check the best response condition:
 - ${\sigma_r^*}_i > 0 \Rightarrow (a\sigma_c^T)_i = \max_{k}(a\sigma_c^T)_k\text{ for all }1\leq i\leq m$
 
Note, for two player games with $m=n=2$, (step 5) is not of importance so to find the best mixed strategy Nash Equilibrium for games of this size is to reduce to finding a solution to two linear equations (step 3). 

### Now lets consider a larger game:
- $A=
   \begin{pmatrix}
   1 & 1 & -1\\
   2 & -1 & 0
   \end{pmatrix}\qquad
   B=
   \begin{pmatrix}
   1/2 & -1 & -1/2\\
   -1 & 3 & 2
   \end{pmatrix}$

1. Note there are no pairs of pure best response.

2. All possible support pairs are:
    - $I=(1, 2)$ and $J=(1, 2)$
    - $I=(1, 2)$ and $J=(1, 3)$
    - $I=(1, 2)$ and $J=(2, 3)$

3. Solve the equations:
    - $I=(1, 2)$ and $J=(1, 2)$:
        - $1/2{\sigma_{r}}_1-{\sigma_{r}}_2=-{\sigma_{r}}_1+3{\sigma_{r}}_2$
        - ${\sigma_{r}}_1=8/3{\sigma_{r}}_2$
        - ${\sigma_{c}}_1+{\sigma_{c}}_2=2{\sigma_{c}}_1-{\sigma_{c}}_2$
        - ${\sigma_{c}}_1=2{\sigma_{c}}_2$
    - $I=(1, 2)$ and $J=(1, 3)$:
        - $1/2{\sigma_{r}}_1-{\sigma_{r}}_2=-1/2{\sigma_{r}}_1+2{\sigma_{r}}_2$
        - ${\sigma_{r}}_1=3{\sigma_{r}}_2$
        - ${\sigma_{c}}_1-{\sigma_{c}}_3=2{\sigma_{c}}_1+0{\sigma_{c}}_3$
        - ${\sigma_{c}}_1=-{\sigma_{c}}_3$
    - $I=(1, 2)$ and $J=(2, 3)$:
        - $-{\sigma_{r}}_1+3{\sigma_{r}}_2=-1/2{\sigma_{r}}_1+2{\sigma_{r}}_2$
        - ${\sigma_{r}}_1=2{\sigma_{r}}_2$
        - ${\sigma_{c}}_2-{\sigma_{c}}_3=-{\sigma_{c}}_2+0{\sigma_{c}}_3$
        - $2{\sigma_{c}}_2={\sigma_{c}}_3$

4. We check which supports give valid mixed strategies:
    - $I=(1, 2)$ and $J=(1, 2)$:
    
        - $\sigma_r=(8/11, 3/11)$
        
        - $\sigma_c=(2/3, 1/3, 0)$
        
    - $I=(1, 2)$ and $J=(1, 3)$:
    
        - $\sigma_r=(3/4, 1/4)$
        
        - $\sigma_c=(k, 0, -k)$     
        
    - $I=(1, 2)$ and $J=(2, 3)$:
    
       - $\sigma_r=(2/3, 1/3)$
        
       - $\sigma_c=(0, 1/3, 2/3)$ 
       
5. Verify the best response condition:

    - $I=(1, 2)$ and $J=(1, 2)$:
    
        - $\sigma_c=(2/3, 1/3, 0)$
        
        - $A\sigma_c^T=
\begin{pmatrix}
1\\
1
\end{pmatrix}$

        - Thus $\sigma_r$ is a best response to $\sigma_c$
        
            - $\sigma_r=(8/11, 3/11)$
        
            - $\sigma_r B=(1/11, 1/11, 2/11)$
            
Here $\sigma_c$ is not a best response to $\sigma_r$, becuase there is a better response outside the support of $\sigma_c$    
- $I=(1, 2)$ and $J=(2, 3):$

  - $\sigma_c=(0, 1/3, 2/3)$
  
  - $A\sigma_c^T=\begin{pmatrix}-1/3\\-1/3\end{pmatrix}$

   - $\sigma_r$ is a best response to $\sigma_c$
    
    

- $\sigma_r=(2/3, 1/3)$

- $\sigma_r B=(0, 1/3, 1/3)$
    
    - $\sigma_c$ is a best response to $\sigma_r$.
    
Thus the unique Nash equilibrium for the game is:
- $((2/3, 1/3), (0, 1/3, 2/3))$


### Now lets confirm our findigs with nashpy python module

In [11]:
# Short game with minimal options
import nashpy as nash
A = np.array([[1,-1], [-1, 1]])
game = nash.Game(A)
list(game.support_enumeration())

[(array([0.5, 0.5]), array([0.5, 0.5]))]

In [12]:
# Long game with more options
A = np.array([[1, 1, -1], [2, -1, 0]]) 
B = np.array([[1/2, -1, -1/2], [-1, 3, 2]])
game = nash.Game(A, B)
list(game.support_enumeration())

[(array([0.66666667, 0.33333333]),
  array([-0.        ,  0.33333333,  0.66666667]))]

In [13]:
# Degenerate game
A = np.array([[1, 1, 0], [2, -1, 0]])
B = np.array([[1/2, -1, -1/2], [-1, 3, 2]])
game = nash.Game(A, B)
list(game.support_enumeration())

/home/sratus/anaconda3/lib/python3.7/site-packages/nashpy/algorithms/support_enumeration.py:196: RuntimeWarning: 
An even number of (0) equilibria was returned. This
indicates that the game is degenerate. Consider using another algorithm
to investigate.
                  
  warnings.warn(warning, RuntimeWarning)


[]